// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO3k_mRHmvyatMAxoTOBio_RvUU_8qhn8',
    appId: '1:176457002209:web:e8d106624efe0a4302dba0',
    messagingSenderId: '176457002209',
    projectId: 'codificandorsa',
    authDomain: 'codificandorsa.firebaseapp.com',
    storageBucket: 'codificandorsa.firebasestorage.app',
    measurementId: 'G-18DNHZTKN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxdX_X5JlPJ05gwUvcoVkN-LzXcC3HFzU',
    appId: '1:176457002209:android:e528b1070152b17f02dba0',
    messagingSenderId: '176457002209',
    projectId: 'codificandorsa',
    storageBucket: 'codificandorsa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA34nDlsctx_VCB4avgHdLKkWDcxYpfCD0',
    appId: '1:176457002209:ios:a97c08f465d3839602dba0',
    messagingSenderId: '176457002209',
    projectId: 'codificandorsa',
    storageBucket: 'codificandorsa.firebasestorage.app',
    iosBundleId: 'com.example.codandoemrsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA34nDlsctx_VCB4avgHdLKkWDcxYpfCD0',
    appId: '1:176457002209:ios:a97c08f465d3839602dba0',
    messagingSenderId: '176457002209',
    projectId: 'codificandorsa',
    storageBucket: 'codificandorsa.firebasestorage.app',
    iosBundleId: 'com.example.codandoemrsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO3k_mRHmvyatMAxoTOBio_RvUU_8qhn8',
    appId: '1:176457002209:web:e4f86aa3fbed1eaf02dba0',
    messagingSenderId: '176457002209',
    projectId: 'codificandorsa',
    authDomain: 'codificandorsa.firebaseapp.com',
    storageBucket: 'codificandorsa.firebasestorage.app',
    measurementId: 'G-F39P5EN6XX',
  );
}
